# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Georgia;text-align:left;display:fill;border-radius:5px;background-color:#254E58;overflow:hidden"><b> Day 29- Numpy Array Sorting   </b>

## Sorting Arrays

* Sorting means putting elements in an ordered sequence.

* Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

* The NumPy ndarray object has a function called sort(), that will sort a specified array.

### Example

**Sort the array:**

In [1]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


### Example
**Sort the array alphabetically:**

In [2]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


### Example
**Sort a boolean array:**

In [3]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


### Sorting a 2-D Array
**If you use the sort() method on a 2-D array, both arrays will be sorted:**

### Example
**Sort a 2-D array:**

In [4]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
