# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Georgia;text-align:left;display:fill;border-radius:5px;background-color:#254E58;overflow:hidden"><b>Day 31- NumPy Random</b></div>

**Random number does NOT mean a different number every time. Random means something that can not be predicted logically.**

## Generate Random Number

**Generate a random integer from 0 to 100:**

In [2]:
from numpy import random

x = random.randint(100)

print(x)

2


### Generate Random Float

**Generate a random float from 0 to 1:**

In [3]:
from numpy import random

x = random.rand()

print(x)

0.38856152514266074


### Generate Random Array

**Generate a 1-D array containing 5 random integers from 0 to 100:**

In [4]:
from numpy import random

x=random.randint(100, size=(5))

print(x)


[79 42 25  5 56]


**Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100**

In [5]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[40 38 59 46 98]
 [79 88 69 47 45]
 [97 27 44 93  8]]


### Floats
**The rand() method also allows you to specify the shape of the array.**

**Generate a 1-D array containing 5 random floats:**

In [6]:
from numpy import random

x = random.rand(5)

print(x)

[0.34731362 0.19153543 0.53500318 0.11921999 0.70446545]


**Generate a 2-D array with 3 rows, each row containing 5 random numbers:**

In [7]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.25167047 0.24695495 0.88199892 0.1239923  0.38590529]
 [0.71695517 0.47318897 0.61777295 0.18190081 0.10430121]
 [0.86773632 0.39068582 0.63482139 0.73929883 0.43782911]]


### Generate Random Number From Array
**The choice() method allows you to generate a random value based on an array of values.**

**The choice() method takes an array as a parameter and randomly returns one of the values**.

### Return one of the values in an array:

In [8]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

5


**Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):**

In [9]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 7 5 5 7]
 [9 9 3 7 9]
 [7 5 3 7 9]]
