# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Georgia;text-align:left;display:fill;border-radius:5px;background-color:#254E58;overflow:hidden"><b>Day 32- Random Data Distribution</b></div>

**Data Distribution is a list of all possible values, and how often each value occurs.**

**Such lists are important when working with statistics and data science.**

**The random module offer methods that returns randomly generated data distributions.**

### Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

**The probability for the value to be 3 is set to be 0.1**

**The probability for the value to be 5 is set to be 0.3**

**The probability for the value to be 7 is set to be 0.6**

**The probability for the value to be 9 is set to be 0**

In [1]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 7 7 7 7 5 7 7 7 3 5 7 7 5 7 7 7 7 5 5 7 7 5 5 5 7 5 7 7 7 7 7 7 7 5
 5 5 7 5 3 7 7 3 5 7 7 7 7 3 5 7 7 5 7 7 5 5 5 7 5 5 7 5 7 5 7 7 7 7 5 7 7
 7 7 7 5 7 7 5 7 7 5 3 5 3 5 7 7 5 7 7 7 3 7 3 5 7 7]


### Same example as above, but return a 2-D array with 3 rows, each containing 5 values.

In [2]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[5 5 5 7 7]
 [5 7 5 7 7]
 [3 3 7 7 7]]
