# <div style="padding:20px;color:white;margin:0;font-size:35px;font-family:Georgia;text-align:left;display:fill;border-radius:5px;background-color:#254E58;overflow:hidden"><b>DAY - 47 ufunc_Simple_Arithmetic. </b></div>

# Simple Arithmetic
**We could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.**

**Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.**

## Addition
The add() function sums the content of two arrays, and return the results in a new array.


### Add the values in arr1 to the values in arr2:

In [1]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


## Subtraction
The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

### Subtract the values in arr2 from the values in arr1:

In [2]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


## Multiplication
The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

### Multiply the values in arr1 with the values in arr2:

In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


## Division
The divide() function divides the values from one array with the values from another array, and return the results in a new array.

### Divide the values in arr1 with the values in arr2:

In [4]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


## Power
The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

### Raise the valules in arr1 to the power of values in arr2:

In [5]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


## Remainder
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

### Return the remainders:

In [6]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


## Quotient and Mod
The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

### Return the quotient and mod:

In [7]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


## Absolute Values
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

### Return the quotient and mod:

In [8]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


## Rounding Decimals

### Rounding Decimals
**There are primarily five ways of rounding off decimals in NumPy:**

* truncation
* fix
* rounding
* floor
* ceil

### Truncation
**Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.**

### Truncate elements of following array:

In [1]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


**Same example, using fix():**



In [2]:
import numpy as np

arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


### Rounding
**The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.**

**E.g. round off to 1 decimal point, 3.16666 is 3.2**

### Round off 3.1666 to 2 decimal places:

In [3]:
import numpy as np

arr = np.around(3.1666, 2)

print(arr)

3.17


### Floor
**The floor() function rounds off decimal to nearest lower integer.**

E.g. floor of 3.166 is 3.

### Floor the elements of following array:

In [4]:
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


### Ceil
**The ceil() function rounds off decimal to nearest upper integer.**

E.g. ceil of 3.166 is 4.

### Ceil the elements of following array:

In [5]:
import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


## NumPy Logs

**Find log at base 2 of all elements of following array:**

In [6]:
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


**Find log at base 10 of all elements of following array:**

In [7]:
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


### Natural Log, or Log at Base e
**Use the log() function to perform log at the base e.**

### Find log at base e of all elements of following array:

In [8]:
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


### Log at Any Base
NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

In [9]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


## NumPy Summations

**Add the values in arr1 to the values in arr2:**

In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


**Sum the values in arr1 and the values in arr2:**

In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


## Summation Over an Axis
**If you specify axis=1, NumPy will sum the numbers in each array.**

**Perform summation in the following array over 1st axis:**

In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


## Cummulative Sum

**Perform cummulative summation in the following array:**

In [13]:
import numpy as np

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


## NumPy Products

**To find the product of the elements in an array, use the prod() function.**

Find the product of the elements of this array:

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


Find the product of the elements of two arrays:

In [16]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


### Product Over an Axis
**If you specify axis=1, NumPy will return the product of each array.**

Perform summation in the following array over 1st axis:

In [18]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


## Cummulative Product

Take cummulative product of all elements for following array:

In [19]:
import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


# NumPy Differences

**Compute discrete difference of the following array:**

In [20]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


**Compute discrete difference of the following array twice:**

In [21]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]


## NumPy LCM Lowest Common Multiple

**Find the LCM of the following two numbers:**

In [22]:
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


**Find the LCM of the values of the following array:**

In [23]:
import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


**Find the LCM of all values of an array where the array contains all integers from 1 to 10:**

In [24]:
import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


## NumPy GCD Greatest Common Denominator

**Find the HCF of the following two numbers:**

In [25]:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


**Find the GCD for all of the numbers in the following array:**

In [26]:
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


## NumPy Trigonometric Functions

**Find sine value of PI/2:**

In [27]:
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


**Find sine values for all of the values in arr:**

In [28]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


**Convert all of the values in following array arr to radians:**

In [29]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


### Radians to Degrees

**Convert all of the values in following array arr to degrees:**

In [30]:
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


**Find the angle of 1.0:**

In [31]:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


**Find the angle for all of the sine values in the array**

In [32]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)


[ 1.57079633 -1.57079633  0.10016742]


## Hypotenues

**Find the hypotenues for 4 base and 3 perpendicular:**

In [33]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


## NumPy Hyperbolic Functions

**Find sinh value of PI/2:**

In [34]:
import numpy as np

x = np.sinh(np.pi/2)

print(x)

2.3012989023072947


**Find cosh values for all of the values in arr:**

In [35]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


## Finding Angles

**Find the angle of 1.0:**

In [36]:
import numpy as np

x = np.arcsinh(1.0)

print(x)

0.881373587019543


### Angles of Each Value in Arrays

**Find the angle for all of the tanh values in array:**

In [37]:
import numpy as np

arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]


## NumPy Set Operations

**Convert following array with repeated elements to a set:**

In [38]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


### Find union of the following two set arrays:

In [39]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


**Find intersection of the following two set arrays:**

In [40]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


**Find the difference of the set1 from set2:**

In [41]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]
